within Simulator.Files.Chemsep_Database;

model General_Properties
  parameter Integer SN;
  parameter String name;
  parameter String CAS;
  parameter Real Tc;
  parameter Real Pc;
  parameter Real Vc;
  parameter Real Cc;
  parameter Real Tb;
  parameter Real Tm;
  parameter Real TT;
  parameter Real TP;
  parameter Real MW;
  parameter Real LVB;
  parameter Real AF;
  parameter Real SP;
  parameter Real DM;
  parameter Real SH;
  parameter Real IGHF;
  parameter Real GEF;
  parameter Real AS;
  parameter Real HFMP;
  parameter Real HOC;
  parameter Real UniquacR;
  parameter Real UniquacQ;
  parameter Real LiqDen[6];
  parameter Real VP[6];
  parameter Real LiqCp[6];
  parameter Real HOV[6];
  parameter Real VapCp[6];
  parameter Real LiqVis[6];
  parameter Real VapVis[6];
  parameter Real LiqK[6];
  parameter Real VapK[6];
  parameter Real Racketparam;
  parameter Real ChaoSeadAF;
  parameter Real ChaoSeadSP;
  parameter Real ChaoSeadLV;
end General_Properties;
